### ISSUE TITLE
Update on documentation maybe?

### ISSUE THREAD

**Issue by victorhg** [ryanong/mongoid_spacial#10]
Hey there, first time trying out mongoid_spacial... :)

I think would be nice to have an update on documentation just noticing that you should run <code>rake db:mongoid:create_indexes</code> once you setup your models...

Just to reduce tracking time when the error <code>Mongo::OperationFailure: can't find special index: 2d for</code> happens 

Can I send a pull request on that?
Cheers :D

**Comment by ryanong** [comment]
Feel free to write a pull request I would accept the help gladly

**Comment by victorhg** [comment]
done :)
