### ISSUE TITLE
DEPRECATION WARNING: The InstanceMethods module inside ActiveSupport::Concern will be no longer included automatically. 

### ISSUE THREAD

**Issue by ikonyshev** [ryanong/mongoid_spacial#20]
I get the following message when run rspec:
**DEPRECATION WARNING: The InstanceMethods module inside ActiveSupport::Concern will be no longer included automatically. Please define instance methods directly in Address instead. (called from include at /Users/ik/Development/projects/booking/webapp/app/models/address.rb:3)**

and line 3 of address.rb is `include Mongoid::Spacial::Document`

The same issue was fixed in mongoid :
https://github.com/mongoid/mongoid/issues/1525

**Comment by mediavrog** [comment]
+1

**Comment by ikonyshev** [comment]
seems it was fixed in this commit - https://github.com/ryanong/mongoid_spacial/commit/1a4841d94dc8d1e432308e648ee1874fc4748cb8

**Comment by al** [comment]
Could we get a tag or version bump for this please?
