### ISSUE TITLE
geo_near Sorting

### ISSUE THREAD

**Issue by rdetert** [ryanong/mongoid_spacial#21]
Am I doing something wrong? It seems that I geo_near automatically always sorts by distance. I'd like to be able to sort by other fields:

@appointments = Appointment.desc(:created_at).geo_near(mycity.coords, :max_distance => @distance, :unit => :mi, :spherical => true)

This always sorts by distance, not created_at

**Comment by ryanong** [comment]
You are using the wrong method.

GeoNear will always sort by distance.

River.where(:source.near => {:point => [-73.98, 40.77], :max => 5})

is the filter
