### ISSUE TITLE
New gem release?

### ISSUE THREAD

**Issue by fbjork** [ryanong/mongoid_spacial#27]
Any chance of seeing a new gem released?

**Comment by ryanong** [comment]
I doubt it. If anybody wants to fork it and correctly name it feel free

-Ryan

On Jun 13, 2012, at 2:19 PM, "Fredrik Björk"
reply@reply.github.com
wrote:

**Comment by fbjork** [comment]
Would love to see a new version with the Rails 3.2 deprecations fixed at least.

**Comment by hilios** [comment]
+1

**Comment by ryanong** [comment]
I have mostly stopped using mongodb. in most cases it is easily overkill and makes ops work quite a bit harder. Now that heroku has postGIS installed by default I mostly use that for my geo locational needs. As for non relational databases I am also moving more towards riak as my DB of choice when the project actually requires a scalable database.

If anybody wants guidance on how to move forward with this project feel free to contact me. Would gladly have a skype conversation about it. This gem in general is a hacky mess before I worked for pivotal labs.

**Comment by arthurnn** [comment]
@fbjork @hilios

I will try to implement all Mongoid 3.0 changes on this gem as soon as possible. For the time being I will close this issues duplicate of #28 .

thanks
