### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by geraudmathe** [ryanong/mongoid_spacial#9]
Hi guys !

While i was reading the documentation, i've seen that you tell to use the method distance_from() with these arguments :

Place.distance_from(:field_source, [-74,40], :mi) 

But il looks that you need to set the unit in a hash like this :

Place.distance_from(:field_source, [-74,40], {:unit=>:mi}) 

Only the second way works for me.
It could be confusing for users

Bye

**Comment by ryanong** [comment]
thx for the report!
